# Generated by Django 5.1.1 on 2024-09-22 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='uui',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='uui',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='uui',
            new_name='uid',
        ),
    ]
