# Generated by Django 5.1.1 on 2024-09-22 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_coupon_alter_product_color_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='uui',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='colorvariant',
            old_name='uui',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='uui',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uui',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='uui',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='sizevariant',
            old_name='uui',
            new_name='uid',
        ),
    ]
